# Script

Fecha de la última revisión

```{r c12-1, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

Sys.Date()
```

------------------------------------------------------------------------

El tema proviene de los siguientes sitios.

English: <https://r4ds.had.co.nz/workflow-scripts.html>

Español: <https://es.r4ds.hadley.nz/06-workflow-scripts.html>

------------------------------------------------------------------------


**Temas super importante**:

## Scripts:

-   Ejecutando códigos
-   Diagnóstico de Rstudio

::: {.consejo}
No copies y pegues en la consola: coloca el cursor en la línea (o selecciona varias) y ejecútala con Cmd/Ctrl+Enter directamente desde el script.
:::

1.  **Ejercicios**:

Hacer los ejercicios en la sección 6.3 del libro en español

```{r c12-2}
library(dplyr)
library(datos)
library(nycflights13)

names(vuelos)
no_cancelado <- vuelos %>% 
  filter(!is.na(atraso_salida), !is.na(atraso_llegada))
head(no_cancelado)

no_cancelado %>% 
  group_by(anio, mes, dia) %>% 
  summarise(media = mean(atraso_salida))
```

```{r c12-3}
x <- 10 
```




