# Appendix D {.unnumbered}

```{r AD1, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

Sys.Date()
```
------------------------------------------------------------------------

*** 

## COVID 19 Cumulativo


Usa los datos de COVID-19 en Puerto Rico (PR) del Departamento de Salud de PR.




```{r AD2}
url_COVID_PR <- read_csv("Datos/url_COVID_PR.csv")

head(url_COVID_PR)


```

***

1. Calcula el promedio acumulativo en periodos de 7 dias.



```{r AD3, warning=FALSE, message=FALSE, echo=FALSE }
Cummulativo=url_COVID_PR %>% 
  dplyr::select(Fecha, IncCasosSaludNuevo) |> 
  dplyr::select(IncCasosSaludNuevo) %>% 
  mutate(Prom_cum=cummean(IncCasosSaludNuevo)) %>% # dplyr:: es para especificar que la función cummean es del paquete dplyr
  mutate(Var_cum=TidyDensity::cvar(IncCasosSaludNuevo)) |> 
  mutate(promedio_coriendo= zoo::rollmean(IncCasosSaludNuevo, k=7, fill=NA, align="left")) |> 
  mutate(varianza_coriendo= zoo::rollapply(IncCasosSaludNuevo, width=7, FUN=var, fill=NA, align="left"))



```

***


2. Haz una figura que muestra el cambio en el promedio cumulativo corriendo de casos nuevos.
```{r AD5, warning=FALSE, message=FALSE, echo=FALSE}

 
  ggplot(Cummulativo, aes(x=1:nrow(url_COVID_PR))) +
  geom_line(aes(y=promedio_coriendo), color="blue") +
  labs(title="Promedio Cumulativo Corriendo de Casos Nuevos de COVID-19 en PR",
       x="Días",
       y="Promedio Cumulativo Corriendo de Casos Nuevos") +
  theme_minimal()


```

