---
title: "Visualization"
author: "Raymond L. Tremblay"
date: "2026-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggversa)
library(datos)



ggplot(Anolis) +
  geom_point(aes(x = SVL, y = TAIL, color=SEX_AGE))+
  facet_wrap(~Survey_Site)
```



```{r}
ggplot(data = millas) +
  geom_point(aes(x = cilindrada, y = autopista))
```


```{r}
ggplot(data = millas) +
  geom_smooth(method=lm,mapping = aes(x = cilindrada, y = autopista))+  # y = mx+b
  geom_point(aes(x = cilindrada, y = autopista))
```



```{r}
ggplot(data = millas) +
  geom_smooth(mapping = aes(x = cilindrada, y = autopista))+  # y = mx+b
  geom_point(aes(x = cilindrada, y = autopista))
```


```{r}
ggplot(diamantes) +
  geom_bar(aes(x = precio))
```



```{r}
ggplot(millas, aes(x = clase, y = autopista)) +
  geom_boxplot()
```



```{r}

d1=c(1,4,8,13,14,15,1000)
d1
median(d1)
mean(d1)
```



```{r}
bar <- ggplot(data = diamantes) +
  geom_bar(aes(x = corte, fill = corte),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar


bar+coord_polar()
```


# titulo

## titullo mas pequeño

### titulo 3

#### titulo 4

**Enegrecido**

*italico*


,hdxcgh;oihjxjtcvlclbvluhvuvhlbvj

```{r}
library(ggplot2)
library(gridExtra)
data <- data.frame(
  Category = c("A", "B", "C", "D"),
  Value = c(20, 30, 40, 10)
)

pie_chart <- ggplot(data, aes(x = "", y = Value, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  labs(fill = "Category")

donut_chart <- pie_chart + 
  geom_bar(data = data, aes(x = "", y = Value), stat = "identity", 
           width = 0.5, fill = "white")+
  theme_void()

pie_chart
donut_chart
```

